AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template is written to run Kittens Carousel Static Website on EC2. 
  Kittens Carousel Static Website will be deployed on Amazon Linux 2023 EC2 Instance with custom 
  security group which allows http connections on port 80 and ssh port 22 from anywhere. Kittens Carousel Static Website
  will be downloaded from my Public Github repository, then be deployed on Apache Web Server.
  
Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64

Resources:

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: tylor
      SecurityGroups:
        - !Ref MySG
      ImageId: !Ref LatestAmiId
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName}
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd wget
          cd /var/www/html
          wget https://raw.githubusercontent.com/muhamedgr/kittensapp-project/main/static-web/index.html
          wget https://raw.githubusercontent.com/muhamedgr/kittensapp-project/main/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/muhamedgr/kittensapp-project/main/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/muhamedgr/kittensapp-project/main/static-web/cat2.jpg
          systemctl start httpd
          systemctl enable httpd


  MySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows HTTP and SSH. # Required
      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80

Outputs:
  KittensCarouselURL:
    Description: Application URL
    Value:
      Fn::Join:
        - ''
        - - 'http://'
          - !GetAtt MyEC2Instance.PublicDnsName
 
